// Mocks generated by Mockito 5.4.4 from annotations
// in experiment_planner/test/blocs/system_state/system_state_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:experiment_planner/blocs/system_state/models/system_state_data.dart'
    as _i5;
import 'package:experiment_planner/features/safety/models/safety_error.dart'
    as _i7;
import 'package:experiment_planner/features/components/models/system_component.dart'
    as _i4;
import 'package:experiment_planner/features/log/models/system_log_entry.dart'
    as _i6;
import 'package:experiment_planner/features/system/repositories/system_state_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SystemStateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemStateRepository extends _i1.Mock
    implements _i2.SystemStateRepository {
  @override
  _i3.Future<void> saveComponentState(
    String? userId,
    _i4.SystemComponent? component,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveComponentState,
          [
            userId,
            component,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveSystemState(Map<String, dynamic>? stateData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSystemState,
          [stateData],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.SystemStateData?> getLatestState() => (super.noSuchMethod(
        Invocation.method(
          #getLatestState,
          [],
        ),
        returnValue: _i3.Future<_i5.SystemStateData?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.SystemStateData?>.value(),
      ) as _i3.Future<_i5.SystemStateData?>);

  @override
  _i3.Stream<_i5.SystemStateData> watchSystemState() => (super.noSuchMethod(
        Invocation.method(
          #watchSystemState,
          [],
        ),
        returnValue: _i3.Stream<_i5.SystemStateData>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.SystemStateData>.empty(),
      ) as _i3.Stream<_i5.SystemStateData>);

  @override
  _i3.Future<_i5.SystemStateData?> getSystemState() => (super.noSuchMethod(
        Invocation.method(
          #getSystemState,
          [],
        ),
        returnValue: _i3.Future<_i5.SystemStateData?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.SystemStateData?>.value(),
      ) as _i3.Future<_i5.SystemStateData?>);

  @override
  _i3.Stream<_i5.SystemStateData?> systemStateStream() => (super.noSuchMethod(
        Invocation.method(
          #systemStateStream,
          [],
        ),
        returnValue: _i3.Stream<_i5.SystemStateData?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.SystemStateData?>.empty(),
      ) as _i3.Stream<_i5.SystemStateData?>);

  @override
  _i3.Future<void> addLogEntry(
    String? userId,
    _i6.SystemLogEntry? logEntry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLogEntry,
          [
            userId,
            logEntry,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SystemComponent>> getAllComponents(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllComponents,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.SystemComponent>>.value(
            <_i4.SystemComponent>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.SystemComponent>>.value(
            <_i4.SystemComponent>[]),
      ) as _i3.Future<List<_i4.SystemComponent>>);

  @override
  _i3.Future<void> saveComponent(
    String? userId,
    _i4.SystemComponent? component,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveComponent,
          [
            userId,
            component,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.SystemComponent?> getComponentByName(
    String? userId,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentByName,
          [
            userId,
            name,
          ],
        ),
        returnValue: _i3.Future<_i4.SystemComponent?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.SystemComponent?>.value(),
      ) as _i3.Future<_i4.SystemComponent?>);

  @override
  _i3.Future<List<_i6.SystemLogEntry>> getAllLogs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLogs,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i6.SystemLogEntry>>.value(<_i6.SystemLogEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.SystemLogEntry>>.value(<_i6.SystemLogEntry>[]),
      ) as _i3.Future<List<_i6.SystemLogEntry>>);

  @override
  _i3.Future<List<_i7.SafetyError>> getAllSafetyErrors(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSafetyErrors,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i7.SafetyError>>.value(<_i7.SafetyError>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.SafetyError>>.value(<_i7.SafetyError>[]),
      ) as _i3.Future<List<_i7.SafetyError>>);

  @override
  _i3.Future<void> saveSafetyError(
    String? userId,
    _i7.SafetyError? safetyError,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSafetyError,
          [
            userId,
            safetyError,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeSafetyError(
    String? userId,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSafetyError,
          [
            userId,
            id,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getComponentHistory(
    String? userId,
    String? componentName,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComponentHistory,
          [
            userId,
            componentName,
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<_i6.SystemLogEntry>> getSystemLog(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSystemLog,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i6.SystemLogEntry>>.value(<_i6.SystemLogEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.SystemLogEntry>>.value(<_i6.SystemLogEntry>[]),
      ) as _i3.Future<List<_i6.SystemLogEntry>>);
}
