name: experiment_planner
description: An app for planning and scheduling experiments.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.4.0
  intl: ^0.19.0
  uuid: ^4.5.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.1
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  bcrypt: ^1.1.3
  table_calendar: ^3.0.8
  flutter_svg: ^2.0.7
  sqflite: ^2.2.8+1
  path: ^1.8.3
  pdf: ^3.10.3
  path_provider: ^2.0.15
  open_file: ^3.2.1
  icon_badge: ^1.0.0
  animated_bottom_navigation_bar: ^1.3.3
  percent_indicator: ^4.2.2
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.1.0
  animated_theme_switcher: ^2.0.8
  glassmorphism: ^3.0.0
  animations: ^2.0.3
  flutter_animate: ^4.1.1+1
  audioplayers: ^6.1.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  crypto: any
  firebase_admin: ^0.3.0
  firebase_dart: ^1.0.11
  http: ^1.2.2
  firebase_auth_rest: ^2.0.6
  bloc: ^8.1.4
  mocktail: ^1.0.0
  flutter_bloc: ^8.1.6
  firebase_crashlytics: ^4.2.0
  mockito: ^5.4.4
  test: ^1.24.9
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^3.1.0
  dartz: ^0.10.1  # For Either type and functional programming
  freezed: ^2.4.7  # For immutable state classes
  get_it: ^7.6.7   # For dependency injection
  injectable: ^2.3.2

  # Routing
  auto_route: ^7.8.4

  # Functional Programming

  # Code Generation
  freezed_annotation: ^2.4.1

  # Utilities
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1

  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/ald_system_diagram.png
    - assets/initial_components.json